# Generated by Django 3.1.2 on 2020-11-28 11:23

import authorization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodesConnecting',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('tempo_password_room', models.CharField(max_length=150, null=True)),
                ('uuid', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=250)),
                ('room', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='URLsUsersFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FileField(upload_to=authorization.models.content_file_name)),
                ('really_name_file', models.CharField(max_length=255)),
                ('id_room', models.IntegerField()),
            ],
        ),
    ]
