# Generated by Django 3.1.2 on 2020-11-29 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='host',
        ),
    ]
