# Generated by Django 3.1.2 on 2020-11-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_remove_rooms_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='host',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
